"""
Batch 3: Add 47 more phones → 100+
"""
import json
from datetime import datetime, timezone

DATA_PATH = '/mnt/c/Users/Reinhart/Desktop/hermes/api-data-service/data/phones.json'

with open(DATA_PATH) as f:
    existing = json.load(f)

existing_keys = {(p['model_name'], p['brand']) for p in existing}
now = datetime.now(timezone.utc).isoformat()

def p(**kw):
    kw['fetched_at'] = now
    return kw

new = [
    # Samsung (6 more)
    p(id="samsung_galaxys24ultra",brand="Samsung",model="Galaxy S24 Ultra",model_name="Galaxy S24 Ultra",
      screen_size="6.8英寸",screen_type="Dynamic LTPO AMOLED 2X",resolution="3120x1440",refresh_rate="120Hz",
      chipset="Snapdragon 8 Gen 3",cpu_cores="8核",gpu="Adreno 750",
      ram="12GB",storage="256GB",storage_expandable=False,
      rear_camera_main="200MP",rear_camera_count="4摄",rear_camera_specs="200MP主摄(OIS)+50MP潜望长焦(5x)+10MP长焦(3x)+12MP超广角",
      front_camera="12MP",video="8K@30fps",
      battery_capacity="5000mAh",charging_wired="45W",charging_wireless="25W",fast_charging=True,
      os="Android 14",network_5g=True,sim_type="Nano-SIM+eSIM",
      weight="232g",dimensions="162.3x79x8.6mm",water_resistance="IP68",material="钛合金边框+玻璃背板",
      fingerprint="超声波屏下",face_unlock=True,nfc=True,infrared=False,headphone_jack=False,
      launch_date="2024-01",source="samsung.com",source_url=""),
    p(id="samsung_galaxys23",brand="Samsung",model="Galaxy S23",model_name="Galaxy S23",
      screen_size="6.1英寸",screen_type="Dynamic AMOLED 2X",resolution="2340x1080",refresh_rate="120Hz",
      chipset="Snapdragon 8 Gen 2",cpu_cores="8核",gpu="Adreno 740",
      ram="8GB",storage="128GB",storage_expandable=False,
      rear_camera_main="50MP",rear_camera_count="3摄",rear_camera_specs="50MP主摄(OIS)+10MP长焦(3x)+12MP超广角",
      front_camera="12MP",video="8K@30fps",
      battery_capacity="3900mAh",charging_wired="25W",charging_wireless="15W",fast_charging=True,
      os="Android 13",network_5g=True,sim_type="Nano-SIM+eSIM",
      weight="168g",dimensions="146.3x70.9x7.6mm",water_resistance="IP68",material="玻璃面板+玻璃背板+铝合金边框",
      fingerprint="超声波屏下",face_unlock=True,nfc=True,infrared=False,headphone_jack=False,
      launch_date="2023-02",source="samsung.com",source_url=""),
    p(id="samsung_galaxys23ultra",brand="Samsung",model="Galaxy S23 Ultra",model_name="Galaxy S23 Ultra",
      screen_size="6.8英寸",screen_type="Dynamic AMOLED 2X",resolution="3088x1440",refresh_rate="120Hz",
      chipset="Snapdragon 8 Gen 2",cpu_cores="8核",gpu="Adreno 740",
      ram="12GB",storage="256GB",storage_expandable=False,
      rear_camera_main="200MP",rear_camera_count="4摄",rear_camera_specs="200MP主摄(OIS)+10MP长焦(3x)+10MP潜望长焦(10x)+12MP超广角",
      front_camera="12MP",video="8K@30fps",
      battery_capacity="5000mAh",charging_wired="45W",charging_wireless="25W",fast_charging=True,
      os="Android 13",network_5g=True,sim_type="Nano-SIM+eSIM",
      weight="234g",dimensions="163.4x78.1x8.9mm",water_resistance="IP68",material="玻璃面板+玻璃背板+铝合金边框",
      fingerprint="超声波屏下",face_unlock=True,nfc=True,infrared=False,headphone_jack=False,
      launch_date="2023-02",source="samsung.com",source_url=""),
    p(id="samsung_galaxya35",brand="Samsung",model="Galaxy A35",model_name="Galaxy A35",
      screen_size="6.6英寸",screen_type="Super AMOLED",resolution="2340x1080",refresh_rate="120Hz",
      chipset="Exynos 1380",cpu_cores="8核",gpu="Mali-G68 MP5",
      ram="6GB",storage="128GB",storage_expandable=True,
      rear_camera_main="50MP",rear_camera_count="3摄",rear_camera_specs="50MP主摄(OIS)+8MP超广角+5MP微距",
      front_camera="13MP",video="4K@30fps",
      battery_capacity="5000mAh",charging_wired="25W",charging_wireless="无",fast_charging=True,
      os="Android 14",network_5g=True,sim_type="Nano-SIM+eSIM",
      weight="209g",dimensions="161.7x78x8.2mm",water_resistance="IP67",material="玻璃面板+塑料背板",
      fingerprint="屏下光学",face_unlock=True,nfc=True,infrared=False,headphone_jack=False,
      launch_date="2024-03",source="samsung.com",source_url=""),
    p(id="samsung_galaxya25",brand="Samsung",model="Galaxy A25",model_name="Galaxy A25",
      screen_size="6.5英寸",screen_type="Super AMOLED",resolution="2340x1080",refresh_rate="120Hz",
      chipset="Exynos 1280",cpu_cores="8核",gpu="Mali-G68",
      ram="6GB",storage="128GB",storage_expandable=True,
      rear_camera_main="50MP",rear_camera_count="3摄",rear_camera_specs="50MP主摄(OIS)+8MP超广角+2MP微距",
      front_camera="13MP",video="4K@30fps",
      battery_capacity="5000mAh",charging_wired="25W",charging_wireless="无",fast_charging=True,
      os="Android 14",network_5g=True,sim_type="Nano-SIM",
      weight="197g",dimensions="161x76.5x8.3mm",water_resistance="IP54",material="塑料背板",
      fingerprint="侧边",face_unlock=True,nfc=True,infrared=False,headphone_jack=True,
      launch_date="2024-01",source="samsung.com",source_url=""),
    p(id="samsung_galaxym55",brand="Samsung",model="Galaxy M55",model_name="Galaxy M55",
      screen_size="6.7英寸",screen_type="Super AMOLED+",resolution="2400x1080",refresh_rate="120Hz",
      chipset="Snapdragon 7 Gen 1",cpu_cores="8核",gpu="Adreno 644",
      ram="8GB",storage="128GB",storage_expandable=True,
      rear_camera_main="50MP",rear_camera_count="3摄",rear_camera_specs="50MP主摄(OIS)+8MP超广角+2MP微距",
      front_camera="50MP",video="4K@30fps",
      battery_capacity="5000mAh",charging_wired="45W",charging_wireless="无",fast_charging=True,
      os="Android 14",network_5g=True,sim_type="Nano-SIM",
      weight="180g",dimensions="163.9x76.5x7.8mm",water_resistance="IP52",material="塑料背板",
      fingerprint="屏下光学",face_unlock=True,nfc=True,infrared=False,headphone_jack=False,
      launch_date="2024-04",source="samsung.com",source_url=""),

    # Apple (3 more)
    p(id="apple_iphone14",brand="Apple",model="iPhone 14",model_name="iPhone 14",
      screen_size="6.1英寸",screen_type="Super Retina XDR OLED",resolution="2532x1170",refresh_rate="60Hz",
      chipset="A15 Bionic",cpu_cores="6核",gpu="Apple 5核GPU",
      ram="6GB",storage="128GB",storage_expandable=False,
      rear_camera_main="12MP",rear_camera_count="2摄",rear_camera_specs="12MP主摄(位移式OIS)+12MP超广角",
      front_camera="12MP",video="4K@60fps",
      battery_capacity="3279mAh",charging_wired="20W",charging_wireless="15W(MagSafe)",fast_charging=True,
      os="iOS 16",network_5g=True,sim_type="Nano-SIM+eSIM",
      weight="172g",dimensions="146.7x71.5x7.8mm",water_resistance="IP68",material="玻璃面板+玻璃背板+铝合金边框",
      fingerprint="无",face_unlock=True,nfc=True,infrared=False,headphone_jack=False,
      launch_date="2022-09",source="apple.com",source_url=""),
    p(id="apple_iphone14pro",brand="Apple",model="iPhone 14 Pro",model_name="iPhone 14 Pro",
      screen_size="6.1英寸",screen_type="Super Retina XDR OLED",resolution="2556x1179",refresh_rate="120Hz",
      chipset="A16 Bionic",cpu_cores="6核",gpu="Apple 5核GPU",
      ram="6GB",storage="128GB",storage_expandable=False,
      rear_camera_main="48MP",rear_camera_count="3摄",rear_camera_specs="48MP主摄(位移式OIS)+12MP长焦(3x)+12MP超广角",
      front_camera="12MP",video="4K@60fps",
      battery_capacity="3200mAh",charging_wired="20W",charging_wireless="15W(MagSafe)",fast_charging=True,
      os="iOS 16",network_5g=True,sim_type="Nano-SIM+eSIM",
      weight="206g",dimensions="147.5x71.5x7.9mm",water_resistance="IP68",material="不锈钢边框+玻璃背板",
      fingerprint="无",face_unlock=True,nfc=True,infrared=False,headphone_jack=False,
      launch_date="2022-09",source="apple.com",source_url=""),
    p(id="apple_iphonese4",brand="Apple",model="iPhone SE 4",model_name="iPhone SE 4",
      screen_size="6.1英寸",screen_type="Super Retina XDR OLED",resolution="2532x1170",refresh_rate="60Hz",
      chipset="A18",cpu_cores="6核",gpu="Apple 4核GPU",
      ram="8GB",storage="128GB",storage_expandable=False,
      rear_camera_main="48MP",rear_camera_count="1摄",rear_camera_specs="48MP主摄(OIS)",
      front_camera="12MP",video="4K@60fps",
      battery_capacity="3279mAh",charging_wired="20W",charging_wireless="15W(MagSafe)",fast_charging=True,
      os="iOS 18",network_5g=True,sim_type="Nano-SIM+eSIM",
      weight="172g",dimensions="146.7x71.5x7.8mm",water_resistance="IP68",material="玻璃面板+玻璃背板+铝合金边框",
      fingerprint="触控ID(电源键)",face_unlock=False,nfc=True,infrared=False,headphone_jack=False,
      launch_date="2025-03",source="apple.com",source_url=""),

    # Google (2 more)
    p(id="google_pixel8pro",brand="Google",model="Pixel 8 Pro",model_name="Pixel 8 Pro",
      screen_size="6.7英寸",screen_type="LTPO OLED",resolution="2992x1344",refresh_rate="120Hz",
      chipset="Tensor G3",cpu_cores="9核",gpu="Immortalis-G715s MC10",
      ram="12GB",storage="128GB",storage_expandable=False,
      rear_camera_main="50MP",rear_camera_count="3摄",rear_camera_specs="50MP主摄(OIS)+48MP长焦(5x)+48MP超广角",
      front_camera="10.5MP",video="4K@60fps",
      battery_capacity="5050mAh",charging_wired="30W",charging_wireless="23W",fast_charging=True,
      os="Android 14",network_5g=True,sim_type="Nano-SIM+eSIM",
      weight="213g",dimensions="162.6x76.5x8.8mm",water_resistance="IP68",material="玻璃面板+玻璃背板+铝合金边框",
      fingerprint="屏下光学",face_unlock=True,nfc=True,infrared=False,headphone_jack=False,
      launch_date="2023-10",source="store.google.com",source_url=""),
    p(id="google_pixel8a",brand="Google",model="Pixel 8a",model_name="Pixel 8a",
      screen_size="6.1英寸",screen_type="OLED",resolution="2400x1080",refresh_rate="120Hz",
      chipset="Tensor G3",cpu_cores="9核",gpu="Immortalis-G715s MC10",
      ram="8GB",storage="128GB",storage_expandable=False,
      rear_camera_main="64MP",rear_camera_count="2摄",rear_camera_specs="64MP主摄(OIS)+13MP超广角",
      front_camera="13MP",video="4K@60fps",
      battery_capacity="4492mAh",charging_wired="18W",charging_wireless="7.5W",fast_charging=True,
      os="Android 14",network_5g=True,sim_type="Nano-SIM+eSIM",
      weight="188g",dimensions="152.1x72.7x8.9mm",water_resistance="IP67",material="塑料背板+铝合金边框",
      fingerprint="屏下光学",face_unlock=True,nfc=True,infrared=False,headphone_jack=False,
      launch_date="2024-05",source="store.google.com",source_url=""),

    # Xiaomi (5 more)
    p(id="xiaomi_13tpro",brand="Xiaomi",model="13T Pro",model_name="13T Pro",
      screen_size="6.67英寸",screen_type="AMOLED",resolution="2712x1220",refresh_rate="144Hz",
      chipset="Dimensity 9200+",cpu_cores="8核",gpu="Immortalis-G715 MC11",
      ram="12GB",storage="512GB",storage_expandable=False,
      rear_camera_main="50MP",rear_camera_count="3摄",rear_camera_specs="50MP主摄(OIS)+50MP长焦(2x)+12MP超广角",
      front_camera="20MP",video="8K@24fps",
      battery_capacity="5000mAh",charging_wired="120W",charging_wireless="无",fast_charging=True,
      os="Android 13, MIUI 14",network_5g=True,sim_type="Nano-SIM+eSIM",
      weight="200g",dimensions="162.2x75.7x8.5mm",water_resistance="IP68",material="玻璃背板+塑料边框",
      fingerprint="屏下光学",face_unlock=True,nfc=True,infrared=True,headphone_jack=False,
      launch_date="2023-09",source="mi.com",source_url=""),
    p(id="xiaomi_redminote13proplus",brand="Xiaomi",model="Redmi Note 13 Pro+",model_name="Redmi Note 13 Pro+",
      screen_size="6.67英寸",screen_type="AMOLED",resolution="2712x1220",refresh_rate="120Hz",
      chipset="Dimensity 7200 Ultra",cpu_cores="8核",gpu="Mali-G610 MC4",
      ram="12GB",storage="256GB",storage_expandable=False,
      rear_camera_main="200MP",rear_camera_count="3摄",rear_camera_specs="200MP主摄(OIS)+8MP超广角+2MP微距",
      front_camera="16MP",video="4K@30fps",
      battery_capacity="5000mAh",charging_wired="120W",charging_wireless="无",fast_charging=True,
      os="Android 13, MIUI 14",network_5g=True,sim_type="Nano-SIM",
      weight="204g",dimensions="161.4x74.2x8.9mm",water_resistance="IP68",material="玻璃背板",
      fingerprint="屏下光学",face_unlock=True,nfc=True,infrared=True,headphone_jack=False,
      launch_date="2023-09",source="mi.com",source_url=""),
    p(id="xiaomi_pocox7pro",brand="Xiaomi",model="Poco X7 Pro",model_name="Poco X7 Pro",
      screen_size="6.67英寸",screen_type="AMOLED",resolution="2712x1220",refresh_rate="120Hz",
      chipset="Dimensity 8400",cpu_cores="8核",gpu="Immortalis-G720 MC7",
      ram="12GB",storage="256GB",storage_expandable=False,
      rear_camera_main="50MP",rear_camera_count="2摄",rear_camera_specs="50MP主摄(OIS)+8MP超广角",
      front_camera="20MP",video="4K@60fps",
      battery_capacity="6000mAh",charging_wired="90W",charging_wireless="无",fast_charging=True,
      os="Android 15, HyperOS 2",network_5g=True,sim_type="Nano-SIM",
      weight="203g",dimensions="160.8x75.2x8.3mm",water_resistance="IP68",material="塑料背板",
      fingerprint="屏下光学",face_unlock=True,nfc=True,infrared=True,headphone_jack=False,
      launch_date="2025-01",source="mi.com",source_url=""),
    p(id="xiaomi_mixfold4",brand="Xiaomi",model="MIX Fold 4",model_name="MIX Fold 4",
      screen_size="7.98英寸",screen_type="Foldable LTPO AMOLED",resolution="2488x2244",refresh_rate="120Hz",
      chipset="Snapdragon 8 Gen 3",cpu_cores="8核",gpu="Adreno 750",
      ram="16GB",storage="512GB",storage_expandable=False,
      rear_camera_main="50MP",rear_camera_count="4摄",rear_camera_specs="50MP主摄(OIS)+10MP长焦(3.2x)+10MP潜望长焦(5x)+12MP超广角",
      front_camera="20MP",video="8K@24fps",
      battery_capacity="5100mAh",charging_wired="67W",charging_wireless="50W",fast_charging=True,
      os="Android 14, HyperOS",network_5g=True,sim_type="Nano-SIM",
      weight="219g",dimensions="159.4x143.3x4.7mm(展开)",water_resistance="无防水",material="玻璃背板+铝合金边框",
      fingerprint="侧边",face_unlock=True,nfc=True,infrared=True,headphone_jack=False,
      launch_date="2024-07",source="mi.com",source_url=""),

    # OnePlus (3 more)
    p(id="oneplus_ace3pro",brand="OnePlus",model="Ace 3 Pro",model_name="Ace 3 Pro",
      screen_size="6.78英寸",screen_type="AMOLED",resolution="2780x1264",refresh_rate="120Hz",
      chipset="Snapdragon 8 Gen 3",cpu_cores="8核",gpu="Adreno 750",
      ram="16GB",storage="256GB",storage_expandable=False,
      rear_camera_main="50MP",rear_camera_count="3摄",rear_camera_specs="50MP主摄(OIS)+8MP超广角+2MP微距",
      front_camera="16MP",video="4K@60fps",
      battery_capacity="6100mAh",charging_wired="100W",charging_wireless="无",fast_charging=True,
      os="Android 14, ColorOS 14",network_5g=True,sim_type="Nano-SIM",
      weight="220g",dimensions="163.3x75.3x8.8mm",water_resistance="IP65",material="玻璃或素皮背板+金属边框",
      fingerprint="屏下光学",face_unlock=True,nfc=True,infrared=True,headphone_jack=False,
      launch_date="2024-06",source="oneplus.com",source_url=""),
    p(id="oneplus_open",brand="OnePlus",model="Open",model_name="Open",
      screen_size="7.82英寸",screen_type="Foldable LTPO3 AMOLED",resolution="2440x2268",refresh_rate="120Hz",
      chipset="Snapdragon 8 Gen 2",cpu_cores="8核",gpu="Adreno 740",
      ram="16GB",storage="512GB",storage_expandable=False,
      rear_camera_main="48MP",rear_camera_count="3摄",rear_camera_specs="48MP主摄(OIS)+64MP长焦(3x,OIS)+48MP超广角",
      front_camera="20MP",video="4K@60fps",
      battery_capacity="4805mAh",charging_wired="67W",charging_wireless="无",fast_charging=True,
      os="Android 13, OxygenOS 13",network_5g=True,sim_type="Nano-SIM",
      weight="239g",dimensions="153.4x143.1x5.8mm(展开)",water_resistance="IPX4",material="玻璃背板+铝合金边框",
      fingerprint="侧边",face_unlock=True,nfc=True,infrared=True,headphone_jack=False,
      launch_date="2023-10",source="oneplus.com",source_url=""),

    # OPPO (1 more)
    p(id="oppo_findx7ultra",brand="OPPO",model="Find X7 Ultra",model_name="Find X7 Ultra",
      screen_size="6.82英寸",screen_type="LTPO AMOLED",resolution="3168x1440",refresh_rate="120Hz",
      chipset="Snapdragon 8 Gen 3",cpu_cores="8核",gpu="Adreno 750",
      ram="16GB",storage="256GB",storage_expandable=False,
      rear_camera_main="50MP",rear_camera_count="4摄",rear_camera_specs="50MP主摄(1英寸)+50MP长焦(3x)+50MP潜望长焦(6x)+50MP超广角",
      front_camera="32MP",video="4K@60fps",
      battery_capacity="5000mAh",charging_wired="100W",charging_wireless="50W",fast_charging=True,
      os="Android 14, ColorOS 14",network_5g=True,sim_type="Nano-SIM",
      weight="221g",dimensions="164.3x76.2x9.5mm",water_resistance="IP68",material="玻璃或素皮背板+铝合金边框",
      fingerprint="屏下光学",face_unlock=True,nfc=True,infrared=True,headphone_jack=False,
      launch_date="2024-01",source="oppo.com",source_url=""),

    # vivo (1 more)
    p(id="vivo_x100pro",brand="vivo",model="X100 Pro",model_name="X100 Pro",
      screen_size="6.78英寸",screen_type="LTPO AMOLED",resolution="2800x1260",refresh_rate="120Hz",
      chipset="Dimensity 9300",cpu_cores="8核",gpu="Immortalis-G720 MC12",
      ram="16GB",storage="512GB",storage_expandable=False,
      rear_camera_main="50MP",rear_camera_count="3摄",rear_camera_specs="50MP主摄(1英寸)+50MP长焦(4.3x)+50MP超广角",
      front_camera="32MP",video="8K@30fps",
      battery_capacity="5400mAh",charging_wired="100W",charging_wireless="50W",fast_charging=True,
      os="Android 14, Funtouch OS 14",network_5g=True,sim_type="Nano-SIM",
      weight="225g",dimensions="164.1x75.3x9.1mm",water_resistance="IP68",material="玻璃背板+铝合金边框",
      fingerprint="屏下光学",face_unlock=True,nfc=True,infrared=True,headphone_jack=False,
      launch_date="2023-11",source="vivo.com",source_url=""),

    # Huawei (2 more)
    p(id="huawei_mate60pro",brand="Huawei",model="Mate 60 Pro",model_name="Mate 60 Pro",
      screen_size="6.82英寸",screen_type="LTPO OLED",resolution="2720x1260",refresh_rate="120Hz",
      chipset="Kirin 9000S",cpu_cores="12核",gpu="Maleoon 910",
      ram="12GB",storage="512GB",storage_expandable=True,
      rear_camera_main="50MP",rear_camera_count="3摄",rear_camera_specs="50MP主摄(OIS)+48MP长焦(3.5x,微距)+12MP超广角",
      front_camera="13MP",video="4K@60fps",
      battery_capacity="5000mAh",charging_wired="88W",charging_wireless="50W",fast_charging=True,
      os="HarmonyOS 4.0",network_5g=True,sim_type="Nano-SIM",
      weight="225g",dimensions="163.7x79x8.1mm",water_resistance="IP68",material="金属+玻璃",
      fingerprint="屏下光学",face_unlock=True,nfc=True,infrared=True,headphone_jack=False,
      launch_date="2023-08",source="huawei.com",source_url=""),
    p(id="huawei_nova13pro",brand="Huawei",model="Nova 13 Pro",model_name="Nova 13 Pro",
      screen_size="6.76英寸",screen_type="OLED",resolution="2776x1224",refresh_rate="120Hz",
      chipset="Kirin 9000SL",cpu_cores="8核",gpu="Maleoon",
      ram="12GB",storage="256GB",storage_expandable=False,
      rear_camera_main="50MP",rear_camera_count="3摄",rear_camera_specs="50MP主摄(OIS)+12MP长焦(3x)+8MP超广角(微距)",
      front_camera="60MP",video="4K@30fps",
      battery_capacity="4600mAh",charging_wired="100W",charging_wireless="无",fast_charging=True,
      os="HarmonyOS 4.0",network_5g=True,sim_type="Nano-SIM",
      weight="199g",dimensions="163.3x74.7x7.8mm",water_resistance="IP53",material="玻璃背板+塑料边框",
      fingerprint="屏下光学",face_unlock=True,nfc=True,infrared=True,headphone_jack=False,
      launch_date="2024-10",source="huawei.com",source_url=""),

    # Motorola (1 more)
    p(id="motorola_edge50pro",brand="Motorola",model="Edge 50 Pro",model_name="Edge 50 Pro",
      screen_size="6.7英寸",screen_type="P-OLED",resolution="2712x1220",refresh_rate="144Hz",
      chipset="Snapdragon 7 Gen 3",cpu_cores="8核",gpu="Adreno 720",
      ram="12GB",storage="256GB",storage_expandable=False,
      rear_camera_main="50MP",rear_camera_count="3摄",rear_camera_specs="50MP主摄(OIS)+10MP长焦(3x)+13MP超广角",
      front_camera="50MP",video="4K@30fps",
      battery_capacity="4500mAh",charging_wired="125W",charging_wireless="50W",fast_charging=True,
      os="Android 14",network_5g=True,sim_type="Nano-SIM+eSIM",
      weight="186g",dimensions="161.2x72.4x8.2mm",water_resistance="IP68",material="素皮或木质背板+铝合金边框",
      fingerprint="屏下光学",face_unlock=True,nfc=True,infrared=False,headphone_jack=False,
      launch_date="2024-04",source="motorola.com",source_url=""),

    # Realme (1 more)
    p(id="realme_12proplus",brand="Realme",model="12 Pro+",model_name="12 Pro+",
      screen_size="6.7英寸",screen_type="AMOLED",resolution="2412x1080",refresh_rate="120Hz",
      chipset="Snapdragon 7s Gen 2",cpu_cores="8核",gpu="Adreno 710",
      ram="8GB",storage="256GB",storage_expandable=False,
      rear_camera_main="50MP",rear_camera_count="3摄",rear_camera_specs="50MP主摄(OIS)+50MP潜望长焦(3x)+8MP超广角",
      front_camera="32MP",video="4K@30fps",
      battery_capacity="5000mAh",charging_wired="67W",charging_wireless="无",fast_charging=True,
      os="Android 14, Realme UI 5",network_5g=True,sim_type="Nano-SIM",
      weight="196g",dimensions="161.5x74x8.8mm",water_resistance="IP65",material="素皮背板",
      fingerprint="屏下光学",face_unlock=True,nfc=True,infrared=False,headphone_jack=False,
      launch_date="2024-01",source="realme.com",source_url=""),

    # Sony (1 more)
    p(id="sony_xperia5vi",brand="Sony",model="Xperia 5 VI",model_name="Xperia 5 VI",
      screen_size="6.1英寸",screen_type="OLED",resolution="2520x1080",refresh_rate="120Hz",
      chipset="Snapdragon 8 Gen 3",cpu_cores="8核",gpu="Adreno 750",
      ram="8GB",storage="128GB",storage_expandable=True,
      rear_camera_main="48MP",rear_camera_count="2摄",rear_camera_specs="48MP主摄(OIS)+12MP超广角",
      front_camera="12MP",video="4K@120fps",
      battery_capacity="4500mAh",charging_wired="30W",charging_wireless="15W",fast_charging=True,
      os="Android 14",network_5g=True,sim_type="Nano-SIM+eSIM",
      weight="168g",dimensions="154x68x8.2mm",water_resistance="IP68",material="玻璃面板+玻璃背板+铝合金边框",
      fingerprint="侧边",face_unlock=False,nfc=True,infrared=False,headphone_jack=True,
      launch_date="2024-09",source="sony.com",source_url=""),

    # --- New brands ---
    p(id="lenovo_legiony90",brand="Lenovo",model="Legion Y90",model_name="Legion Y90",
      screen_size="6.92英寸",screen_type="AMOLED",resolution="2460x1080",refresh_rate="144Hz",
      chipset="Snapdragon 8 Gen 1",cpu_cores="8核",gpu="Adreno 730",
      ram="18GB",storage="512GB",storage_expandable=False,
      rear_camera_main="64MP",rear_camera_count="2摄",rear_camera_specs="64MP主摄+13MP超广角",
      front_camera="16MP",video="4K@60fps",
      battery_capacity="5600mAh",charging_wired="68W",charging_wireless="无",fast_charging=True,
      os="Android 12",network_5g=True,sim_type="Nano-SIM",
      weight="252g",dimensions="176x78.5x10.1mm",water_resistance="无防水",material="玻璃背板+铝合金边框",
      fingerprint="屏下光学",face_unlock=True,nfc=True,infrared=False,headphone_jack=True,
      launch_date="2022-05",source="lenovo.com",source_url=""),

    p(id="zte_axon50ultra",brand="ZTE",model="Axon 50 Ultra",model_name="Axon 50 Ultra",
      screen_size="6.67英寸",screen_type="AMOLED",resolution="2400x1080",refresh_rate="144Hz",
      chipset="Snapdragon 8+ Gen 1",cpu_cores="8核",gpu="Adreno 730",
      ram="12GB",storage="256GB",storage_expandable=False,
      rear_camera_main="64MP",rear_camera_count="3摄",rear_camera_specs="64MP主摄(OIS)+50MP长焦(3x)+50MP超广角",
      front_camera="32MP",video="4K@60fps",
      battery_capacity="5000mAh",charging_wired="80W",charging_wireless="无",fast_charging=True,
      os="Android 13",network_5g=True,sim_type="Nano-SIM",
      weight="199g",dimensions="161.5x73x8.5mm",water_resistance="IP54",material="玻璃背板+铝合金边框",
      fingerprint="屏下光学",face_unlock=True,nfc=True,infrared=False,headphone_jack=False,
      launch_date="2023-04",source="zte.com.cn",source_url=""),

    p(id="nokia_x30",brand="Nokia",model="X30 5G",model_name="X30 5G",
      screen_size="6.43英寸",screen_type="AMOLED",resolution="2400x1080",refresh_rate="90Hz",
      chipset="Snapdragon 695",cpu_cores="8核",gpu="Adreno 619",
      ram="8GB",storage="256GB",storage_expandable=False,
      rear_camera_main="50MP",rear_camera_count="2摄",rear_camera_specs="50MP主摄(OIS)+13MP超广角",
      front_camera="16MP",video="1080p@60fps",
      battery_capacity="4200mAh",charging_wired="33W",charging_wireless="无",fast_charging=True,
      os="Android 12",network_5g=True,sim_type="Nano-SIM",
      weight="185g",dimensions="158.9x73.9x8mm",water_resistance="IP67",material="回收铝合金边框+塑料背板",
      fingerprint="屏下光学",face_unlock=True,nfc=True,infrared=False,headphone_jack=False,
      launch_date="2022-09",source="nokia.com",source_url=""),

    p(id="fairphone_5",brand="Fairphone",model="Fairphone 5",model_name="Fairphone 5",
      screen_size="6.46英寸",screen_type="OLED",resolution="2700x1224",refresh_rate="90Hz",
      chipset="Snapdragon QCM6490",cpu_cores="8核",gpu="Adreno 643L",
      ram="8GB",storage="256GB",storage_expandable=True,
      rear_camera_main="50MP",rear_camera_count="2摄",rear_camera_specs="50MP主摄(OIS)+50MP超广角",
      front_camera="50MP",video="4K@30fps",
      battery_capacity="4200mAh",charging_wired="20W",charging_wireless="无",fast_charging=False,
      os="Android 13",network_5g=True,sim_type="Nano-SIM+eSIM",
      weight="212g",dimensions="161.6x75.8x9.6mm",water_resistance="IP55",material="回收塑料 可拆卸模块化设计",
      fingerprint="侧边",face_unlock=True,nfc=True,infrared=False,headphone_jack=False,
      launch_date="2023-08",source="fairphone.com",source_url=""),

    p(id="unihertz_tank3",brand="Unihertz",model="Tank 3",model_name="Tank 3",
      screen_size="6.79英寸",screen_type="IPS LCD",resolution="2460x1080",refresh_rate="120Hz",
      chipset="Dimensity 8200",cpu_cores="8核",gpu="Mali-G610 MC6",
      ram="16GB",storage="512GB",storage_expandable=False,
      rear_camera_main="200MP",rear_camera_count="3摄",rear_camera_specs="200MP主摄+50MP超广角+64MP夜视",
      front_camera="32MP",video="4K@30fps",
      battery_capacity="23800mAh",charging_wired="120W",charging_wireless="无",fast_charging=True,
      os="Android 13",network_5g=True,sim_type="Nano-SIM",
      weight="671g",dimensions="179x86x31mm",water_resistance="IP69K",material="橡胶+金属 三防加固",
      fingerprint="侧边",face_unlock=True,nfc=False,infrared=False,headphone_jack=True,
      launch_date="2024-04",source="unihertz.com",source_url=""),

    p(id="cat_s75",brand="Cat",model="S75",model_name="S75",
      screen_size="6.6英寸",screen_type="IPS LCD",resolution="2408x1080",refresh_rate="120Hz",
      chipset="Dimensity 930",cpu_cores="8核",gpu="IMG BXM-8-256",
      ram="6GB",storage="128GB",storage_expandable=True,
      rear_camera_main="50MP",rear_camera_count="3摄",rear_camera_specs="50MP主摄+8MP超广角+2MP微距",
      front_camera="8MP",video="1080p@30fps",
      battery_capacity="5000mAh",charging_wired="15W",charging_wireless="无",fast_charging=False,
      os="Android 12",network_5g=True,sim_type="Nano-SIM+eSIM",
      weight="268g",dimensions="171x80x11.9mm",water_resistance="IP69/IP68",material="橡胶+金属 军工级加固",
      fingerprint="后置",face_unlock=True,nfc=True,infrared=False,headphone_jack=True,
      launch_date="2023-02",source="catphones.com",source_url=""),

    # Tecno, Infinix, itel more
    p(id="tecno_camon30premier",brand="Tecno",model="Camon 30 Premier",model_name="Camon 30 Premier",
      screen_size="6.77英寸",screen_type="LTPO AMOLED",resolution="2780x1264",refresh_rate="120Hz",
      chipset="Dimensity 8200 Ultimate",cpu_cores="8核",gpu="Mali-G610 MC6",
      ram="12GB",storage="512GB",storage_expandable=False,
      rear_camera_main="50MP",rear_camera_count="3摄",rear_camera_specs="50MP主摄(OIS)+50MP长焦(3x)+50MP超广角",
      front_camera="50MP",video="4K@60fps",
      battery_capacity="5000mAh",charging_wired="70W",charging_wireless="无",fast_charging=True,
      os="Android 14, HiOS 14",network_5g=True,sim_type="Nano-SIM",
      weight="198g",dimensions="162.7x76.2x7.9mm",water_resistance="IP54",material="玻璃背板+铝合金边框",
      fingerprint="屏下光学",face_unlock=True,nfc=True,infrared=False,headphone_jack=False,
      launch_date="2024-02",source="tecno-mobile.com",source_url=""),

    p(id="infinix_gt20pro",brand="Infinix",model="GT 20 Pro",model_name="GT 20 Pro",
      screen_size="6.78英寸",screen_type="AMOLED",resolution="2436x1080",refresh_rate="144Hz",
      chipset="Dimensity 8200 Ultimate",cpu_cores="8核",gpu="Mali-G610 MC6",
      ram="12GB",storage="256GB",storage_expandable=False,
      rear_camera_main="108MP",rear_camera_count="3摄",rear_camera_specs="108MP主摄(OIS)+2MP微距+2MP景深",
      front_camera="32MP",video="4K@60fps",
      battery_capacity="5000mAh",charging_wired="100W",charging_wireless="无",fast_charging=True,
      os="Android 14, XOS 14",network_5g=True,sim_type="Nano-SIM",
      weight="198g",dimensions="164.3x74.5x8.2mm",water_resistance="IP54",material="玻璃背板+塑料边框",
      fingerprint="屏下光学",face_unlock=True,nfc=True,infrared=False,headphone_jack=True,
      launch_date="2024-04",source="infinixmobility.com",source_url=""),

    p(id="cmf_phone1",brand="Nothing",model="CMF Phone 1",model_name="CMF Phone 1",
      screen_size="6.67英寸",screen_type="AMOLED",resolution="2400x1080",refresh_rate="120Hz",
      chipset="Dimensity 7300",cpu_cores="8核",gpu="Mali-G615 MC2",
      ram="8GB",storage="128GB",storage_expandable=True,
      rear_camera_main="50MP",rear_camera_count="2摄",rear_camera_specs="50MP主摄+2MP景深",
      front_camera="16MP",video="4K@30fps",
      battery_capacity="5000mAh",charging_wired="33W",charging_wireless="无",fast_charging=True,
      os="Android 14, Nothing OS 2.6",network_5g=True,sim_type="Nano-SIM",
      weight="202g",dimensions="164x77x8.2mm",water_resistance="IP52",material="塑料背板 可更换后盖",
      fingerprint="屏下光学",face_unlock=True,nfc=False,infrared=False,headphone_jack=False,
      launch_date="2024-07",source="nothing.tech",source_url=""),

    p(id="xiaomi_pocom7pro",brand="Xiaomi",model="Poco M7 Pro",model_name="Poco M7 Pro",
      screen_size="6.67英寸",screen_type="AMOLED",resolution="2400x1080",refresh_rate="120Hz",
      chipset="Dimensity 7025 Ultra",cpu_cores="8核",gpu="IMG BXM-8-256",
      ram="8GB",storage="256GB",storage_expandable=True,
      rear_camera_main="50MP",rear_camera_count="2摄",rear_camera_specs="50MP主摄+2MP景深",
      front_camera="20MP",video="1080p@30fps",
      battery_capacity="5110mAh",charging_wired="45W",charging_wireless="无",fast_charging=True,
      os="Android 14, HyperOS",network_5g=True,sim_type="Nano-SIM",
      weight="191g",dimensions="162.3x74.3x8.2mm",water_resistance="IP64",material="塑料背板",
      fingerprint="屏下光学",face_unlock=True,nfc=True,infrared=True,headphone_jack=True,
      launch_date="2025-01",source="mi.com",source_url=""),
]

added = 0
skipped = 0
for phone in new:
    key = (phone['model_name'], phone['brand'])
    if key not in existing_keys:
        existing.append(phone)
        existing_keys.add(key)
        added += 1
    else:
        skipped += 1

print(f"Batch 3: Added {added}, skipped {skipped} (duplicates)")

with open(DATA_PATH, 'w') as f:
    json.dump(existing, f, ensure_ascii=False, indent=2)

brands = {}
for p in existing:
    brands[p['brand']] = brands.get(p['brand'], 0) + 1
print(f"Total: {len(existing)} phones, {len(brands)} brands")
for b, c in sorted(brands.items(), key=lambda x: -x[1]):
    print(f"  {b}: {c}")
