"""
Add more phones matching the existing phones.json schema (38 fields).
"""
import json, os
from datetime import datetime

DATA_PATH = '/mnt/c/Users/Reinhart/Desktop/hermes/api-data-service/data/phones.json'

with open(DATA_PATH) as f:
    existing = json.load(f)

existing_keys = {(p['model_name'], p['brand']) for p in existing}
now = datetime.utcnow().isoformat() + 'Z'

new_phones = [
    {
        "id": "samsung_galaxys25",
        "brand": "Samsung", "model": "Galaxy S25", "model_name": "Galaxy S25",
        "screen_size": "6.2英寸", "screen_type": "Dynamic LTPO AMOLED 2X",
        "resolution": "2340x1080", "refresh_rate": "120Hz",
        "chipset": "Snapdragon 8 Elite", "cpu_cores": "8核", "gpu": "Adreno 830",
        "ram": "12GB", "storage": "128GB", "storage_expandable": False,
        "rear_camera_main": "50MP", "rear_camera_count": "3摄",
        "rear_camera_specs": "50MP主摄(OIS)+10MP长焦(3x)+12MP超广角",
        "front_camera": "12MP", "video": "8K@30fps",
        "battery_capacity": "4000mAh", "charging_wired": "25W", "charging_wireless": "15W",
        "fast_charging": True,
        "os": "Android 15", "network_5g": True, "sim_type": "Nano-SIM+eSIM",
        "weight": "162g", "dimensions": "146.9x70.5x7.2mm",
        "water_resistance": "IP68", "material": "玻璃面板+玻璃背板+铝合金边框",
        "fingerprint": "超声波屏下", "face_unlock": True, "nfc": True,
        "infrared": False, "headphone_jack": False,
        "launch_date": "2025-01", "source": "samsung.com", "source_url": "",
        "fetched_at": now,
    },
    {
        "id": "samsung_galaxys25ultra",
        "brand": "Samsung", "model": "Galaxy S25 Ultra", "model_name": "Galaxy S25 Ultra",
        "screen_size": "6.9英寸", "screen_type": "Dynamic LTPO AMOLED 2X",
        "resolution": "3120x1440", "refresh_rate": "120Hz",
        "chipset": "Snapdragon 8 Elite", "cpu_cores": "8核", "gpu": "Adreno 830",
        "ram": "12GB", "storage": "256GB", "storage_expandable": False,
        "rear_camera_main": "200MP", "rear_camera_count": "4摄",
        "rear_camera_specs": "200MP主摄(OIS)+50MP潜望长焦(5x)+10MP长焦(3x)+50MP超广角",
        "front_camera": "12MP", "video": "8K@30fps",
        "battery_capacity": "5000mAh", "charging_wired": "45W", "charging_wireless": "25W",
        "fast_charging": True,
        "os": "Android 15", "network_5g": True, "sim_type": "Nano-SIM+eSIM",
        "weight": "218g", "dimensions": "162.8x77.6x8.2mm",
        "water_resistance": "IP68", "material": "钛合金边框+玻璃背板",
        "fingerprint": "超声波屏下", "face_unlock": True, "nfc": True,
        "infrared": False, "headphone_jack": False,
        "launch_date": "2025-01", "source": "samsung.com", "source_url": "",
        "fetched_at": now,
    },
    {
        "id": "samsung_galaxyzfold7",
        "brand": "Samsung", "model": "Galaxy Z Fold 7", "model_name": "Galaxy Z Fold 7",
        "screen_size": "7.8英寸", "screen_type": "Foldable Dynamic LTPO AMOLED 2X",
        "resolution": "2176x1812", "refresh_rate": "120Hz",
        "chipset": "Snapdragon 8 Elite Gen 2", "cpu_cores": "8核", "gpu": "Adreno 840",
        "ram": "12GB", "storage": "256GB", "storage_expandable": False,
        "rear_camera_main": "50MP", "rear_camera_count": "3摄",
        "rear_camera_specs": "50MP主摄(OIS)+10MP长焦(3x)+12MP超广角",
        "front_camera": "10MP", "video": "8K@30fps",
        "battery_capacity": "4400mAh", "charging_wired": "45W", "charging_wireless": "25W",
        "fast_charging": True,
        "os": "Android 16", "network_5g": True, "sim_type": "Nano-SIM+eSIM",
        "weight": "239g", "dimensions": "155.1x130.1x5.6mm(展开)",
        "water_resistance": "IP48", "material": "玻璃面板+玻璃背板+铝合金边框",
        "fingerprint": "侧边", "face_unlock": True, "nfc": True,
        "infrared": False, "headphone_jack": False,
        "launch_date": "2025-07", "source": "samsung.com", "source_url": "",
        "fetched_at": now,
    },
    {
        "id": "google_pixel10pro",
        "brand": "Google", "model": "Pixel 10 Pro", "model_name": "Pixel 10 Pro",
        "screen_size": "6.3英寸", "screen_type": "LTPO OLED",
        "resolution": "2856x1280", "refresh_rate": "120Hz",
        "chipset": "Tensor G5", "cpu_cores": "8核", "gpu": "Mali-G715",
        "ram": "16GB", "storage": "128GB", "storage_expandable": False,
        "rear_camera_main": "50MP", "rear_camera_count": "3摄",
        "rear_camera_specs": "50MP主摄(OIS)+48MP潜望长焦(5x)+48MP超广角",
        "front_camera": "42MP", "video": "8K@30fps",
        "battery_capacity": "4870mAh", "charging_wired": "30W", "charging_wireless": "23W",
        "fast_charging": True,
        "os": "Android 16", "network_5g": True, "sim_type": "Nano-SIM+eSIM",
        "weight": "207g", "dimensions": "152.8x72x8.5mm",
        "water_resistance": "IP68", "material": "玻璃面板+玻璃背板+铝合金边框",
        "fingerprint": "超声波屏下", "face_unlock": True, "nfc": True,
        "infrared": False, "headphone_jack": False,
        "launch_date": "2025-08", "source": "store.google.com", "source_url": "",
        "fetched_at": now,
    },
    {
        "id": "google_pixel10",
        "brand": "Google", "model": "Pixel 10", "model_name": "Pixel 10",
        "screen_size": "6.3英寸", "screen_type": "OLED",
        "resolution": "2424x1080", "refresh_rate": "120Hz",
        "chipset": "Tensor G5", "cpu_cores": "8核", "gpu": "Mali-G715",
        "ram": "12GB", "storage": "128GB", "storage_expandable": False,
        "rear_camera_main": "50MP", "rear_camera_count": "2摄",
        "rear_camera_specs": "50MP主摄(OIS)+48MP超广角",
        "front_camera": "10.5MP", "video": "4K@60fps",
        "battery_capacity": "4700mAh", "charging_wired": "27W", "charging_wireless": "15W",
        "fast_charging": True,
        "os": "Android 16", "network_5g": True, "sim_type": "Nano-SIM+eSIM",
        "weight": "192g", "dimensions": "152.8x72x8.9mm",
        "water_resistance": "IP68", "material": "玻璃面板+玻璃背板+铝合金边框",
        "fingerprint": "屏下光学", "face_unlock": True, "nfc": True,
        "infrared": False, "headphone_jack": False,
        "launch_date": "2025-08", "source": "store.google.com", "source_url": "",
        "fetched_at": now,
    },
    {
        "id": "google_pixel9pro",
        "brand": "Google", "model": "Pixel 9 Pro", "model_name": "Pixel 9 Pro",
        "screen_size": "6.3英寸", "screen_type": "LTPO OLED",
        "resolution": "2856x1280", "refresh_rate": "120Hz",
        "chipset": "Tensor G4", "cpu_cores": "8核", "gpu": "Mali-G715",
        "ram": "16GB", "storage": "128GB", "storage_expandable": False,
        "rear_camera_main": "50MP", "rear_camera_count": "3摄",
        "rear_camera_specs": "50MP主摄(OIS)+48MP潜望长焦(5x)+48MP超广角",
        "front_camera": "42MP", "video": "8K@30fps",
        "battery_capacity": "4700mAh", "charging_wired": "27W", "charging_wireless": "21W",
        "fast_charging": True,
        "os": "Android 14", "network_5g": True, "sim_type": "Nano-SIM+eSIM",
        "weight": "199g", "dimensions": "152.8x72x8.5mm",
        "water_resistance": "IP68", "material": "玻璃面板+玻璃背板+铝合金边框",
        "fingerprint": "超声波屏下", "face_unlock": True, "nfc": True,
        "infrared": False, "headphone_jack": False,
        "launch_date": "2024-08", "source": "store.google.com", "source_url": "",
        "fetched_at": now,
    },
    {
        "id": "google_pixel9a",
        "brand": "Google", "model": "Pixel 9a", "model_name": "Pixel 9a",
        "screen_size": "6.3英寸", "screen_type": "OLED",
        "resolution": "2424x1080", "refresh_rate": "120Hz",
        "chipset": "Tensor G4", "cpu_cores": "8核", "gpu": "Mali-G715",
        "ram": "8GB", "storage": "128GB", "storage_expandable": False,
        "rear_camera_main": "48MP", "rear_camera_count": "2摄",
        "rear_camera_specs": "48MP主摄(OIS)+13MP超广角",
        "front_camera": "13MP", "video": "4K@60fps",
        "battery_capacity": "5100mAh", "charging_wired": "23W", "charging_wireless": "7.5W",
        "fast_charging": True,
        "os": "Android 15", "network_5g": True, "sim_type": "Nano-SIM+eSIM",
        "weight": "193g", "dimensions": "154.7x73.2x8.9mm",
        "water_resistance": "IP67", "material": "塑料背板+铝合金边框",
        "fingerprint": "屏下光学", "face_unlock": True, "nfc": True,
        "infrared": False, "headphone_jack": False,
        "launch_date": "2025-03", "source": "store.google.com", "source_url": "",
        "fetched_at": now,
    },
    {
        "id": "apple_iphone15",
        "brand": "Apple", "model": "iPhone 15", "model_name": "iPhone 15",
        "screen_size": "6.1英寸", "screen_type": "Super Retina XDR OLED",
        "resolution": "2556x1179", "refresh_rate": "60Hz",
        "chipset": "A16 Bionic", "cpu_cores": "6核", "gpu": "Apple 5核GPU",
        "ram": "6GB", "storage": "128GB", "storage_expandable": False,
        "rear_camera_main": "48MP", "rear_camera_count": "2摄",
        "rear_camera_specs": "48MP主摄(位移式OIS)+12MP超广角",
        "front_camera": "12MP", "video": "4K@60fps",
        "battery_capacity": "3349mAh", "charging_wired": "20W", "charging_wireless": "15W(MagSafe)",
        "fast_charging": True,
        "os": "iOS 17", "network_5g": True, "sim_type": "Nano-SIM+eSIM",
        "weight": "171g", "dimensions": "147.6x71.6x7.8mm",
        "water_resistance": "IP68", "material": "玻璃面板+玻璃背板+铝合金边框",
        "fingerprint": "无", "face_unlock": True, "nfc": True,
        "infrared": False, "headphone_jack": False,
        "launch_date": "2023-09", "source": "apple.com", "source_url": "",
        "fetched_at": now,
    },
    {
        "id": "nothing_phone3",
        "brand": "Nothing", "model": "Phone (3)", "model_name": "Phone (3)",
        "screen_size": "6.67英寸", "screen_type": "LTPO AMOLED",
        "resolution": "2800x1260", "refresh_rate": "120Hz",
        "chipset": "Snapdragon 8s Elite", "cpu_cores": "8核", "gpu": "Adreno 740",
        "ram": "12GB", "storage": "256GB", "storage_expandable": False,
        "rear_camera_main": "50MP", "rear_camera_count": "3摄",
        "rear_camera_specs": "50MP主摄(OIS)+50MP长焦(2x)+50MP超广角",
        "front_camera": "32MP", "video": "4K@60fps",
        "battery_capacity": "5000mAh", "charging_wired": "45W", "charging_wireless": "15W",
        "fast_charging": True,
        "os": "Android 15", "network_5g": True, "sim_type": "Nano-SIM",
        "weight": "218g", "dimensions": "163.5x77.5x9mm",
        "water_resistance": "IP65", "material": "玻璃面板+玻璃背板+铝合金边框+Glyph灯带",
        "fingerprint": "屏下光学", "face_unlock": True, "nfc": True,
        "infrared": False, "headphone_jack": False,
        "launch_date": "2025-07", "source": "nothing.tech", "source_url": "",
        "fetched_at": now,
    },
    {
        "id": "nothing_phone3a",
        "brand": "Nothing", "model": "Phone (3a)", "model_name": "Phone (3a)",
        "screen_size": "6.7英寸", "screen_type": "AMOLED",
        "resolution": "2412x1080", "refresh_rate": "120Hz",
        "chipset": "Snapdragon 7s Gen 3", "cpu_cores": "8核", "gpu": "Adreno 730",
        "ram": "8GB", "storage": "128GB", "storage_expandable": False,
        "rear_camera_main": "50MP", "rear_camera_count": "3摄",
        "rear_camera_specs": "50MP主摄(OIS)+50MP长焦(2x)+50MP超广角",
        "front_camera": "32MP", "video": "4K@30fps",
        "battery_capacity": "5000mAh", "charging_wired": "45W", "charging_wireless": "无",
        "fast_charging": True,
        "os": "Android 15", "network_5g": True, "sim_type": "Nano-SIM",
        "weight": "201g", "dimensions": "163.5x77.5x8.2mm",
        "water_resistance": "IP54", "material": "玻璃面板+塑料背板+Glyph灯带",
        "fingerprint": "屏下光学", "face_unlock": True, "nfc": True,
        "infrared": False, "headphone_jack": False,
        "launch_date": "2025-03", "source": "nothing.tech", "source_url": "",
        "fetched_at": now,
    },
    {
        "id": "motorola_edge2025",
        "brand": "Motorola", "model": "Edge (2025)", "model_name": "Edge (2025)",
        "screen_size": "6.7英寸", "screen_type": "P-OLED",
        "resolution": "2712x1220", "refresh_rate": "120Hz",
        "chipset": "Dimensity 7400 Ultra", "cpu_cores": "8核", "gpu": "Mali-G615 MC2",
        "ram": "8GB", "storage": "256GB", "storage_expandable": False,
        "rear_camera_main": "50MP", "rear_camera_count": "3摄",
        "rear_camera_specs": "50MP主摄(OIS)+10MP长焦(3x,OIS)+50MP超广角",
        "front_camera": "50MP", "video": "4K@30fps",
        "battery_capacity": "5200mAh", "charging_wired": "68W", "charging_wireless": "15W",
        "fast_charging": True,
        "os": "Android 15", "network_5g": True, "sim_type": "Nano-SIM+eSIM",
        "weight": "181g", "dimensions": "161.2x73.1x8mm",
        "water_resistance": "IP68/IP69", "material": "玻璃面板+塑料背板+铝合金边框",
        "fingerprint": "屏下光学", "face_unlock": True, "nfc": True,
        "infrared": False, "headphone_jack": False,
        "launch_date": "2025-05", "source": "gsmarena.com", "source_url": "https://www.gsmarena.com/motorola_edge_(2025)-13907.php",
        "fetched_at": now,
    },
]

# Add only new
added = 0
for phone in new_phones:
    key = (phone['model_name'], phone['brand'])
    if key not in existing_keys:
        existing.append(phone)
        existing_keys.add(key)
        added += 1

print(f"Added {added} new phones")

# Save
with open(DATA_PATH, 'w') as f:
    json.dump(existing, f, ensure_ascii=False, indent=2)

print(f"Total: {len(existing)} phones, {len(set(p['brand'] for p in existing))} brands")

# Show brand distribution
brands = {}
for p in existing:
    brands[p['brand']] = brands.get(p['brand'], 0) + 1
for b, c in sorted(brands.items(), key=lambda x: -x[1]):
    print(f"  {b}: {c}")
