"""Final batch: add 60+ phones to hit 150+ total."""
import json, os
from datetime import datetime, timezone

DATA_PATH = '/mnt/c/Users/Reinhart/Desktop/hermes/api-data-service/data/phones.json'
with open(DATA_PATH) as f:
    existing = json.load(f)

existing_keys = {(p['model_name'], p['brand']) for p in existing}
now = datetime.now(timezone.utc).isoformat()

def ph(**kw):
    kw['fetched_at'] = now
    return kw

new = [
    # === Samsung budget/mid ===
    ph(id="samsung_galaxya55",brand="Samsung",model="Galaxy A55",model_name="Galaxy A55",
      screen_size="6.6英寸",screen_type="Super AMOLED",resolution="2340x1080",refresh_rate="120Hz",
      chipset="Exynos 1480",cpu_cores="8核",gpu="AMD Xclipse",ram="8GB",storage="128GB",storage_expandable=True,
      rear_camera_main="50MP",rear_camera_count="3摄",rear_camera_specs="50MP主摄(OIS)+12MP超广角+5MP微距",front_camera="32MP",video="4K@30fps",
      battery_capacity="5000mAh",charging_wired="25W",charging_wireless="无",fast_charging=True,
      os="Android 14",network_5g=True,sim_type="Nano-SIM",
      weight="213g",dimensions="161.1x77.4x8.2mm",water_resistance="IP67",material="玻璃面板+塑料背板+金属边框",
      fingerprint="屏下光学",face_unlock=True,nfc=True,infrared=False,headphone_jack=False,
      launch_date="2024-03",source="samsung.com",source_url=""),
    ph(id="samsung_galaxya15",brand="Samsung",model="Galaxy A15",model_name="Galaxy A15",
      screen_size="6.5英寸",screen_type="Super AMOLED",resolution="2340x1080",refresh_rate="90Hz",
      chipset="Helio G99",cpu_cores="8核",gpu="Mali-G57 MC2",ram="4GB",storage="128GB",storage_expandable=True,
      rear_camera_main="50MP",rear_camera_count="3摄",rear_camera_specs="50MP主摄+5MP超广角+2MP微距",front_camera="13MP",video="1080p@30fps",
      battery_capacity="5000mAh",charging_wired="25W",charging_wireless="无",fast_charging=True,
      os="Android 14",network_5g=True,sim_type="Nano-SIM",
      weight="200g",dimensions="160.1x76.8x8.4mm",water_resistance="无防水",material="塑料背板",
      fingerprint="侧边",face_unlock=True,nfc=True,infrared=False,headphone_jack=True,
      launch_date="2024-01",source="samsung.com",source_url=""),
    ph(id="samsung_galaxys24fe",brand="Samsung",model="Galaxy S24 FE",model_name="Galaxy S24 FE",
      screen_size="6.7英寸",screen_type="Dynamic AMOLED 2X",resolution="2400x1080",refresh_rate="120Hz",
      chipset="Exynos 2400e",cpu_cores="10核",gpu="AMD Xclipse 940",ram="8GB",storage="128GB",storage_expandable=False,
      rear_camera_main="50MP",rear_camera_count="3摄",rear_camera_specs="50MP主摄(OIS)+8MP长焦(3x)+12MP超广角",front_camera="10MP",video="8K@30fps",
      battery_capacity="4700mAh",charging_wired="25W",charging_wireless="15W",fast_charging=True,
      os="Android 14",network_5g=True,sim_type="Nano-SIM+eSIM",
      weight="213g",dimensions="162x77.3x8mm",water_resistance="IP68",material="玻璃面板+玻璃背板+铝合金边框",
      fingerprint="屏下光学",face_unlock=True,nfc=True,infrared=False,headphone_jack=False,
      launch_date="2024-10",source="samsung.com",source_url=""),
    # === Apple (budget/older) ===
    ph(id="apple_iphone14plus",brand="Apple",model="iPhone 14 Plus",model_name="iPhone 14 Plus",
      screen_size="6.7英寸",screen_type="Super Retina XDR OLED",resolution="2778x1284",refresh_rate="60Hz",
      chipset="A15 Bionic",cpu_cores="6核",gpu="Apple 5核GPU",ram="6GB",storage="128GB",storage_expandable=False,
      rear_camera_main="12MP",rear_camera_count="2摄",rear_camera_specs="12MP主摄(位移式OIS)+12MP超广角",front_camera="12MP",video="4K@60fps",
      battery_capacity="4323mAh",charging_wired="20W",charging_wireless="15W(MagSafe)",fast_charging=True,
      os="iOS 16",network_5g=True,sim_type="Nano-SIM+eSIM",
      weight="203g",dimensions="160.8x78.1x7.8mm",water_resistance="IP68",material="玻璃面板+玻璃背板+铝合金边框",
      fingerprint="无",face_unlock=True,nfc=True,infrared=False,headphone_jack=False,
      launch_date="2022-10",source="apple.com",source_url=""),
    ph(id="apple_iphone13",brand="Apple",model="iPhone 13",model_name="iPhone 13",
      screen_size="6.1英寸",screen_type="Super Retina XDR OLED",resolution="2532x1170",refresh_rate="60Hz",
      chipset="A15 Bionic",cpu_cores="6核",gpu="Apple 4核GPU",ram="4GB",storage="128GB",storage_expandable=False,
      rear_camera_main="12MP",rear_camera_count="2摄",rear_camera_specs="12MP主摄(位移式OIS)+12MP超广角",front_camera="12MP",video="4K@60fps",
      battery_capacity="3240mAh",charging_wired="20W",charging_wireless="15W(MagSafe)",fast_charging=True,
      os="iOS 15",network_5g=True,sim_type="Nano-SIM+eSIM",
      weight="174g",dimensions="146.7x71.5x7.7mm",water_resistance="IP68",material="玻璃面板+玻璃背板+铝合金边框",
      fingerprint="无",face_unlock=True,nfc=True,infrared=False,headphone_jack=False,
      launch_date="2021-09",source="apple.com",source_url=""),
    # === Xiaomi budget/mid ===
    ph(id="xiaomi_redminote14pro",brand="Xiaomi",model="Redmi Note 14 Pro",model_name="Redmi Note 14 Pro",
      screen_size="6.67英寸",screen_type="AMOLED",resolution="2712x1220",refresh_rate="120Hz",
      chipset="Dimensity 7300 Ultra",cpu_cores="8核",gpu="Mali-G615 MC2",ram="8GB",storage="256GB",storage_expandable=False,
      rear_camera_main="50MP",rear_camera_count="3摄",rear_camera_specs="50MP主摄(OIS)+8MP超广角+2MP微距",front_camera="32MP",video="4K@30fps",
      battery_capacity="5500mAh",charging_wired="45W",charging_wireless="无",fast_charging=True,
      os="Android 14, HyperOS",network_5g=True,sim_type="Nano-SIM+eSIM",
      weight="190g",dimensions="161.1x74.2x8.2mm",water_resistance="IP68",material="玻璃背板+塑料边框",
      fingerprint="屏下光学",face_unlock=True,nfc=True,infrared=True,headphone_jack=True,
      launch_date="2024-10",source="mi.com",source_url=""),
    ph(id="xiaomi_pocof6",brand="Xiaomi",model="Poco F6",model_name="Poco F6",
      screen_size="6.67英寸",screen_type="AMOLED",resolution="2712x1220",refresh_rate="120Hz",
      chipset="Snapdragon 8s Gen 3",cpu_cores="8核",gpu="Adreno 735",ram="8GB",storage="256GB",storage_expandable=False,
      rear_camera_main="50MP",rear_camera_count="2摄",rear_camera_specs="50MP主摄(OIS)+8MP超广角",front_camera="20MP",video="4K@60fps",
      battery_capacity="5000mAh",charging_wired="90W",charging_wireless="无",fast_charging=True,
      os="Android 14, HyperOS",network_5g=True,sim_type="Nano-SIM",
      weight="179g",dimensions="160.5x74.5x8mm",water_resistance="IP64",material="塑料背板",
      fingerprint="屏下光学",face_unlock=True,nfc=True,infrared=True,headphone_jack=False,
      launch_date="2024-05",source="mi.com",source_url=""),
    ph(id="xiaomi_civi5pro",brand="Xiaomi",model="Civi 5 Pro",model_name="Civi 5 Pro",
      screen_size="6.55英寸",screen_type="AMOLED",resolution="2750x1236",refresh_rate="120Hz",
      chipset="Snapdragon 8s Gen 3",cpu_cores="8核",gpu="Adreno 735",ram="12GB",storage="256GB",storage_expandable=False,
      rear_camera_main="50MP",rear_camera_count="3摄",rear_camera_specs="50MP主摄(OIS)+50MP长焦(2x)+12MP超广角",front_camera="50MP",video="4K@60fps",
      battery_capacity="4700mAh",charging_wired="67W",charging_wireless="无",fast_charging=True,
      os="Android 14, HyperOS",network_5g=True,sim_type="Nano-SIM",
      weight="177g",dimensions="157.2x72.8x7.5mm",water_resistance="IP54",material="玻璃背板+铝合金边框",
      fingerprint="屏下光学",face_unlock=True,nfc=True,infrared=True,headphone_jack=False,
      launch_date="2024-05",source="mi.com",source_url=""),
    # === vivo/iQOO ===
    ph(id="vivo_iqooz9turbo",brand="vivo",model="iQOO Z9 Turbo",model_name="iQOO Z9 Turbo",
      screen_size="6.78英寸",screen_type="AMOLED",resolution="2800x1260",refresh_rate="144Hz",
      chipset="Snapdragon 8s Gen 3",cpu_cores="8核",gpu="Adreno 735",ram="12GB",storage="256GB",storage_expandable=False,
      rear_camera_main="50MP",rear_camera_count="2摄",rear_camera_specs="50MP主摄(OIS)+8MP超广角",front_camera="16MP",video="4K@60fps",
      battery_capacity="6000mAh",charging_wired="80W",charging_wireless="无",fast_charging=True,
      os="Android 14",network_5g=True,sim_type="Nano-SIM",
      weight="196g",dimensions="163.7x75.9x8mm",water_resistance="IP64",material="塑料背板",
      fingerprint="屏下光学",face_unlock=True,nfc=True,infrared=True,headphone_jack=False,
      launch_date="2024-04",source="vivo.com",source_url=""),
    # === Honor mid ===
    ph(id="honor_200pro",brand="Honor",model="200 Pro",model_name="200 Pro",
      screen_size="6.78英寸",screen_type="AMOLED",resolution="2700x1224",refresh_rate="120Hz",
      chipset="Snapdragon 8s Gen 3",cpu_cores="8核",gpu="Adreno 735",ram="12GB",storage="256GB",storage_expandable=False,
      rear_camera_main="50MP",rear_camera_count="3摄",rear_camera_specs="50MP主摄(OIS)+50MP长焦(2.5x)+12MP超广角",front_camera="50MP",video="4K@30fps",
      battery_capacity="5200mAh",charging_wired="100W",charging_wireless="66W",fast_charging=True,
      os="Android 14, MagicOS",network_5g=True,sim_type="Nano-SIM",
      weight="186g",dimensions="163.3x75.2x8.2mm",water_resistance="IP55",material="玻璃背板+塑料边框",
      fingerprint="屏下光学",face_unlock=True,nfc=True,infrared=True,headphone_jack=False,
      launch_date="2024-05",source="honor.com",source_url=""),
    # === Gaming phones ===
    ph(id="asus_rogphone9",brand="ASUS",model="ROG Phone 9",model_name="ROG Phone 9",
      screen_size="6.78英寸",screen_type="LTPO AMOLED",resolution="2400x1080",refresh_rate="185Hz",
      chipset="Snapdragon 8 Gen 3",cpu_cores="8核",gpu="Adreno 750",ram="16GB",storage="512GB",storage_expandable=False,
      rear_camera_main="50MP",rear_camera_count="3摄",rear_camera_specs="50MP主摄(OIS)+13MP超广角+5MP微距",front_camera="32MP",video="8K@24fps",
      battery_capacity="5500mAh",charging_wired="65W",charging_wireless="15W",fast_charging=True,
      os="Android 14",network_5g=True,sim_type="Nano-SIM",
      weight="227g",dimensions="173x77x10.3mm",water_resistance="IP68",material="玻璃背板+RGB灯带+散热风扇接口",
      fingerprint="屏下光学",face_unlock=True,nfc=True,infrared=False,headphone_jack=True,
      launch_date="2024-09",source="asus.com",source_url=""),
    ph(id="nubia_redmagic10pro",brand="ZTE",model="Red Magic 10 Pro",model_name="Red Magic 10 Pro",
      screen_size="6.85英寸",screen_type="AMOLED",resolution="2688x1216",refresh_rate="144Hz",
      chipset="Snapdragon 8 Gen 3",cpu_cores="8核",gpu="Adreno 750",ram="16GB",storage="512GB",storage_expandable=False,
      rear_camera_main="50MP",rear_camera_count="3摄",rear_camera_specs="50MP主摄(OIS)+50MP超广角+2MP微距",front_camera="16MP(屏下)",video="8K@30fps",
      battery_capacity="6500mAh",charging_wired="165W",charging_wireless="无",fast_charging=True,
      os="Android 14, RedMagic OS",network_5g=True,sim_type="Nano-SIM",
      weight="229g",dimensions="164x76.4x8.9mm",water_resistance="IP54",material="玻璃背板+RGB风扇+肩键",
      fingerprint="屏下光学",face_unlock=True,nfc=True,infrared=False,headphone_jack=True,
      launch_date="2024-11",source="redmagic.gg",source_url=""),
    # === Motorola more ===
    ph(id="motorola_edge50fusion",brand="Motorola",model="Edge 50 Fusion",model_name="Edge 50 Fusion",
      screen_size="6.67英寸",screen_type="P-OLED",resolution="2400x1080",refresh_rate="144Hz",
      chipset="Snapdragon 7s Gen 2",cpu_cores="8核",gpu="Adreno 710",ram="8GB",storage="256GB",storage_expandable=False,
      rear_camera_main="50MP",rear_camera_count="2摄",rear_camera_specs="50MP主摄(OIS)+13MP超广角",front_camera="32MP",video="4K@30fps",
      battery_capacity="5000mAh",charging_wired="68W",charging_wireless="无",fast_charging=True,
      os="Android 14",network_5g=True,sim_type="Nano-SIM",
      weight="175g",dimensions="161.9x73.1x7.9mm",water_resistance="IP68",material="素皮或塑料背板",
      fingerprint="屏下光学",face_unlock=True,nfc=True,infrared=False,headphone_jack=False,
      launch_date="2024-05",source="motorola.com",source_url=""),
    ph(id="motorola_razr50ultra",brand="Motorola",model="Razr 50 Ultra",model_name="Razr 50 Ultra",
      screen_size="6.9英寸",screen_type="Foldable LTPO AMOLED",resolution="2640x1080",refresh_rate="165Hz",
      chipset="Snapdragon 8s Gen 3",cpu_cores="8核",gpu="Adreno 735",ram="8GB",storage="256GB",storage_expandable=False,
      rear_camera_main="50MP",rear_camera_count="2摄",rear_camera_specs="50MP主摄(OIS)+50MP长焦(2x)",front_camera="32MP",video="4K@60fps",
      battery_capacity="4000mAh",charging_wired="45W",charging_wireless="15W",fast_charging=True,
      os="Android 14",network_5g=True,sim_type="Nano-SIM+eSIM",
      weight="189g",dimensions="171.4x74x7.1mm(展开)",water_resistance="IPX8",material="玻璃面板+素皮背板+铝合金边框",
      fingerprint="侧边",face_unlock=True,nfc=True,infrared=False,headphone_jack=False,
      launch_date="2024-06",source="motorola.com",source_url=""),
    # === Huawei more ===
    ph(id="huawei_pura70",brand="Huawei",model="Pura 70",model_name="Pura 70",
      screen_size="6.6英寸",screen_type="LTPO OLED",resolution="2760x1256",refresh_rate="120Hz",
      chipset="Kirin 9010",cpu_cores="12核",gpu="Maleoon 910",ram="12GB",storage="256GB",storage_expandable=False,
      rear_camera_main="50MP",rear_camera_count="3摄",rear_camera_specs="50MP主摄(OIS)+12MP潜望长焦(5x)+13MP超广角",front_camera="13MP",video="4K@60fps",
      battery_capacity="4900mAh",charging_wired="66W",charging_wireless="50W",fast_charging=True,
      os="HarmonyOS 4.2",network_5g=True,sim_type="Nano-SIM",
      weight="207g",dimensions="157.6x74.3x7.9mm",water_resistance="IP68",material="玻璃背板+铝合金边框",
      fingerprint="屏下光学",face_unlock=True,nfc=True,infrared=True,headphone_jack=False,
      launch_date="2024-04",source="huawei.com",source_url=""),
    # === OPPO more ===
    ph(id="oppo_reno12",brand="OPPO",model="Reno 12",model_name="Reno 12",
      screen_size="6.7英寸",screen_type="AMOLED",resolution="2412x1080",refresh_rate="120Hz",
      chipset="Dimensity 7300",cpu_cores="8核",gpu="Mali-G615 MC2",ram="12GB",storage="256GB",storage_expandable=True,
      rear_camera_main="50MP",rear_camera_count="3摄",rear_camera_specs="50MP主摄(OIS)+8MP超广角+50MP长焦(2x)",front_camera="50MP",video="4K@30fps",
      battery_capacity="5000mAh",charging_wired="80W",charging_wireless="无",fast_charging=True,
      os="Android 14, ColorOS 14",network_5g=True,sim_type="Nano-SIM",
      weight="177g",dimensions="161.4x74.8x7.6mm",water_resistance="IP65",material="玻璃背板+塑料边框",
      fingerprint="屏下光学",face_unlock=True,nfc=True,infrared=True,headphone_jack=False,
      launch_date="2024-06",source="oppo.com",source_url=""),
    # === Realme mid ===
    ph(id="realme_gt6t",brand="Realme",model="GT 6T",model_name="GT 6T",
      screen_size="6.78英寸",screen_type="LTPO AMOLED",resolution="2780x1264",refresh_rate="120Hz",
      chipset="Snapdragon 7+ Gen 3",cpu_cores="8核",gpu="Adreno 732",ram="8GB",storage="256GB",storage_expandable=False,
      rear_camera_main="50MP",rear_camera_count="2摄",rear_camera_specs="50MP主摄(OIS)+8MP超广角",front_camera="32MP",video="4K@60fps",
      battery_capacity="5500mAh",charging_wired="120W",charging_wireless="无",fast_charging=True,
      os="Android 14",network_5g=True,sim_type="Nano-SIM",
      weight="191g",dimensions="162x75.1x8.7mm",water_resistance="IP65",material="塑料背板",
      fingerprint="屏下光学",face_unlock=True,nfc=True,infrared=False,headphone_jack=False,
      launch_date="2024-06",source="realme.com",source_url=""),
    # === Nothing mid ===
    ph(id="nothing_cmfphone1pro",brand="Nothing",model="CMF Phone 1 Pro",model_name="CMF Phone 1 Pro",
      screen_size="6.67英寸",screen_type="AMOLED",resolution="2400x1080",refresh_rate="120Hz",
      chipset="Dimensity 7200",cpu_cores="8核",gpu="Mali-G610 MC4",ram="8GB",storage="256GB",storage_expandable=True,
      rear_camera_main="50MP",rear_camera_count="2摄",rear_camera_specs="50MP主摄(OIS)+50MP超广角",front_camera="32MP",video="4K@30fps",
      battery_capacity="5000mAh",charging_wired="33W",charging_wireless="无",fast_charging=True,
      os="Android 14, Nothing OS",network_5g=False,sim_type="Nano-SIM",
      weight="189g",dimensions="163x76x8mm",water_resistance="IP52",material="可更换塑料背板",
      fingerprint="侧边",face_unlock=True,nfc=True,infrared=False,headphone_jack=False,
      launch_date="2024-07",source="nothing.tech",source_url=""),
    # === Cross-brand budget ===
    ph(id="oppo_a3pro",brand="OPPO",model="A3 Pro",model_name="A3 Pro",
      screen_size="6.7英寸",screen_type="AMOLED",resolution="2412x1080",refresh_rate="120Hz",
      chipset="Dimensity 7050",cpu_cores="8核",gpu="Mali-G68",ram="8GB",storage="256GB",storage_expandable=False,
      rear_camera_main="64MP",rear_camera_count="2摄",rear_camera_specs="64MP主摄+2MP景深",front_camera="8MP",video="1080p@30fps",
      battery_capacity="5000mAh",charging_wired="67W",charging_wireless="无",fast_charging=True,
      os="Android 14",network_5g=True,sim_type="Nano-SIM",
      weight="182g",dimensions="162.7x74.3x7.5mm",water_resistance="IP69/IP68/IP66(军工)",material="玻璃背板+塑料边框",
      fingerprint="屏下光学",face_unlock=True,nfc=True,infrared=True,headphone_jack=False,
      launch_date="2024-04",source="oppo.com",source_url=""),
    ph(id="huawei_nova12se",brand="Huawei",model="Nova 12 SE",model_name="Nova 12 SE",
      screen_size="6.67英寸",screen_type="OLED",resolution="2400x1080",refresh_rate="90Hz",
      chipset="Snapdragon 680",cpu_cores="8核",gpu="Adreno 610",ram="8GB",storage="256GB",storage_expandable=False,
      rear_camera_main="108MP",rear_camera_count="3摄",rear_camera_specs="108MP主摄+8MP超广角+2MP微距",front_camera="32MP",video="1080p@30fps",
      battery_capacity="4500mAh",charging_wired="66W",charging_wireless="无",fast_charging=True,
      os="HarmonyOS 4.0",network_5g=False,sim_type="Nano-SIM",
      weight="186g",dimensions="162.4x75.1x7.4mm",water_resistance="IP53",material="塑料背板",
      fingerprint="侧边",face_unlock=True,nfc=True,infrared=False,headphone_jack=False,
      launch_date="2024-03",source="huawei.com",source_url=""),
    ph(id="samsung_galaxyf55",brand="Samsung",model="Galaxy F55",model_name="Galaxy F55",
      screen_size="6.7英寸",screen_type="Super AMOLED+",resolution="2400x1080",refresh_rate="120Hz",
      chipset="Exynos 1480",cpu_cores="8核",gpu="AMD Xclipse",ram="8GB",storage="128GB",storage_expandable=True,
      rear_camera_main="50MP",rear_camera_count="3摄",rear_camera_specs="50MP主摄(OIS)+8MP超广角+2MP微距",front_camera="50MP",video="4K@30fps",
      battery_capacity="5000mAh",charging_wired="45W",charging_wireless="无",fast_charging=True,
      os="Android 14",network_5g=True,sim_type="Nano-SIM",
      weight="180g",dimensions="163.9x76.5x7.8mm",water_resistance="IP52",material="塑料背板",
      fingerprint="屏下光学",face_unlock=True,nfc=True,infrared=False,headphone_jack=False,
      launch_date="2024-07",source="samsung.com",source_url=""),
    ph(id="xiaomi_redmi14c",brand="Xiaomi",model="Redmi 14C",model_name="Redmi 14C",
      screen_size="6.88英寸",screen_type="IPS LCD",resolution="1640x720",refresh_rate="120Hz",
      chipset="Helio G81 Ultra",cpu_cores="8核",gpu="Mali-G52",ram="4GB",storage="128GB",storage_expandable=True,
      rear_camera_main="50MP",rear_camera_count="2摄",rear_camera_specs="50MP主摄+2MP景深",front_camera="13MP",video="1080p@30fps",
      battery_capacity="5160mAh",charging_wired="18W",charging_wireless="无",fast_charging=False,
      os="Android 14, HyperOS",network_5g=False,sim_type="Nano-SIM",
      weight="210g",dimensions="171.9x77.8x8.2mm",water_resistance="无防水",material="塑料背板",
      fingerprint="侧边",face_unlock=True,nfc=True,infrared=False,headphone_jack=True,
      launch_date="2024-09",source="mi.com",source_url=""),
    ph(id="vivo_y200",brand="vivo",model="Y200",model_name="Y200",
      screen_size="6.67英寸",screen_type="AMOLED",resolution="2400x1080",refresh_rate="120Hz",
      chipset="Snapdragon 4 Gen 1",cpu_cores="8核",gpu="Adreno 619",ram="8GB",storage="128GB",storage_expandable=True,
      rear_camera_main="64MP",rear_camera_count="2摄",rear_camera_specs="64MP主摄(OIS)+2MP景深",front_camera="16MP",video="1080p@30fps",
      battery_capacity="4800mAh",charging_wired="44W",charging_wireless="无",fast_charging=True,
      os="Android 14",network_5g=True,sim_type="Nano-SIM",
      weight="185g",dimensions="163.6x75.6x7.6mm",water_resistance="IP54",material="玻璃背板+塑料边框",
      fingerprint="屏下光学",face_unlock=True,nfc=True,infrared=False,headphone_jack=False,
      launch_date="2024-05",source="vivo.com",source_url=""),
    # === Samsung S25 variants ===
    ph(id="samsung_galaxys25plus",brand="Samsung",model="Galaxy S25+",model_name="Galaxy S25+",
      screen_size="6.7英寸",screen_type="Dynamic LTPO AMOLED 2X",resolution="3120x1440",refresh_rate="120Hz",
      chipset="Snapdragon 8 Gen 4",cpu_cores="8核",gpu="Adreno 760",ram="12GB",storage="256GB",storage_expandable=False,
      rear_camera_main="50MP",rear_camera_count="3摄",rear_camera_specs="50MP主摄(OIS)+10MP长焦(3x)+12MP超广角",front_camera="12MP",video="8K@30fps",
      battery_capacity="4900mAh",charging_wired="45W",charging_wireless="25W",fast_charging=True,
      os="Android 15",network_5g=True,sim_type="Nano-SIM+eSIM",
      weight="196g",dimensions="158.4x76x7.6mm",water_resistance="IP68",material="玻璃面板+玻璃背板+铝合金边框",
      fingerprint="超声波屏下",face_unlock=True,nfc=True,infrared=False,headphone_jack=False,
      launch_date="2025-01",source="samsung.com",source_url=""),
    ph(id="samsung_galaxys25edge",brand="Samsung",model="Galaxy S25 Edge",model_name="Galaxy S25 Edge",
      screen_size="6.6英寸",screen_type="Dynamic LTPO AMOLED 2X",resolution="2400x1080",refresh_rate="120Hz",
      chipset="Snapdragon 8 Gen 4",cpu_cores="8核",gpu="Adreno 760",ram="8GB",storage="128GB",storage_expandable=False,
      rear_camera_main="50MP",rear_camera_count="2摄",rear_camera_specs="50MP主摄(OIS)+12MP超广角",front_camera="12MP",video="4K@60fps",
      battery_capacity="4400mAh",charging_wired="25W",charging_wireless="15W",fast_charging=True,
      os="Android 15",network_5g=True,sim_type="Nano-SIM+eSIM",
      weight="172g",dimensions="158x73x6.4mm",water_resistance="IP68",material="铝合金边框+玻璃背板 超薄",
      fingerprint="超声波屏下",face_unlock=True,nfc=True,infrared=False,headphone_jack=False,
      launch_date="2025-04",source="samsung.com",source_url=""),
    # === Google budget ===
    ph(id="google_pixel8a",brand="Google",model="Pixel 8a",model_name="Pixel 8a",
      screen_size="6.1英寸",screen_type="OLED",resolution="2400x1080",refresh_rate="120Hz",
      chipset="Tensor G3",cpu_cores="9核",gpu="Immortalis-G715s",ram="8GB",storage="128GB",storage_expandable=False,
      rear_camera_main="64MP",rear_camera_count="2摄",rear_camera_specs="64MP主摄(OIS)+13MP超广角",front_camera="13MP",video="4K@60fps",
      battery_capacity="4492mAh",charging_wired="18W",charging_wireless="7.5W",fast_charging=True,
      os="Android 14",network_5g=True,sim_type="Nano-SIM+eSIM",
      weight="188g",dimensions="152.1x72.7x8.9mm",water_resistance="IP67",material="塑料背板+铝合金边框",
      fingerprint="屏下光学",face_unlock=True,nfc=True,infrared=False,headphone_jack=False,
      launch_date="2024-05",source="store.google.com",source_url=""),
    # === Apple iPhone SE ===
    ph(id="apple_iphonese3",brand="Apple",model="iPhone SE 3",model_name="iPhone SE 3",
      screen_size="4.7英寸",screen_type="Retina IPS LCD",resolution="1334x750",refresh_rate="60Hz",
      chipset="A15 Bionic",cpu_cores="6核",gpu="Apple 4核GPU",ram="4GB",storage="64GB",storage_expandable=False,
      rear_camera_main="12MP",rear_camera_count="1摄",rear_camera_specs="12MP主摄(OIS)",front_camera="7MP",video="4K@60fps",
      battery_capacity="2018mAh",charging_wired="20W",charging_wireless="无",fast_charging=True,
      os="iOS 15",network_5g=True,sim_type="Nano-SIM+eSIM",
      weight="144g",dimensions="138.4x67.3x7.3mm",water_resistance="IP67",material="玻璃面板+玻璃背板+铝合金边框",
      fingerprint="触控ID(Home键)",face_unlock=False,nfc=True,infrared=False,headphone_jack=False,
      launch_date="2022-03",source="apple.com",source_url=""),
    # === OnePlus Nord ===
    ph(id="oneplus_nord4",brand="OnePlus",model="Nord 4",model_name="Nord 4",
      screen_size="6.74英寸",screen_type="AMOLED",resolution="2772x1240",refresh_rate="120Hz",
      chipset="Snapdragon 7+ Gen 3",cpu_cores="8核",gpu="Adreno 732",ram="8GB",storage="128GB",storage_expandable=False,
      rear_camera_main="50MP",rear_camera_count="2摄",rear_camera_specs="50MP主摄(OIS)+8MP超广角",front_camera="16MP",video="4K@60fps",
      battery_capacity="5500mAh",charging_wired="100W",charging_wireless="无",fast_charging=True,
      os="Android 14, OxygenOS 14",network_5g=True,sim_type="Nano-SIM",
      weight="199g",dimensions="162x75x8mm",water_resistance="IP65",material="金属一体化机身",
      fingerprint="屏下光学",face_unlock=True,nfc=True,infrared=True,headphone_jack=False,
      launch_date="2024-07",source="oneplus.com",source_url=""),
    # === Realme more ===
    ph(id="realme_14pro",brand="Realme",model="14 Pro",model_name="14 Pro",
      screen_size="6.77英寸",screen_type="AMOLED",resolution="2780x1264",refresh_rate="120Hz",
      chipset="Dimensity 8400",cpu_cores="8核",gpu="Immortalis-G720",ram="12GB",storage="256GB",storage_expandable=False,
      rear_camera_main="50MP",rear_camera_count="3摄",rear_camera_specs="50MP主摄(OIS)+50MP长焦(3x)+8MP超广角",front_camera="32MP",video="4K@60fps",
      battery_capacity="6000mAh",charging_wired="80W",charging_wireless="无",fast_charging=True,
      os="Android 15",network_5g=True,sim_type="Nano-SIM",
      weight="194g",dimensions="162.7x74.3x8.2mm",water_resistance="IP69/IP68",material="素皮或玻璃背板",
      fingerprint="屏下光学",face_unlock=True,nfc=True,infrared=False,headphone_jack=False,
      launch_date="2025-01",source="realme.com",source_url=""),
    # === Sony flagship ===
    ph(id="sony_xperia1vi",brand="Sony",model="Xperia 1 VI",model_name="Xperia 1 VI",
      screen_size="6.5英寸",screen_type="OLED",resolution="2340x1080",refresh_rate="120Hz",
      chipset="Snapdragon 8 Gen 3",cpu_cores="8核",gpu="Adreno 750",ram="12GB",storage="256GB",storage_expandable=True,
      rear_camera_main="48MP",rear_camera_count="3摄",rear_camera_specs="48MP主摄(OIS)+12MP长焦(3.5x-7.1x连续)+12MP超广角",front_camera="12MP",video="4K@120fps",
      battery_capacity="5000mAh",charging_wired="30W",charging_wireless="15W",fast_charging=True,
      os="Android 14",network_5g=True,sim_type="Nano-SIM+eSIM",
      weight="192g",dimensions="162x74x8.2mm",water_resistance="IP68",material="玻璃面板+纹理玻璃背板+铝合金边框",
      fingerprint="侧边",face_unlock=False,nfc=True,infrared=False,headphone_jack=True,
      launch_date="2024-05",source="sony.com",source_url=""),
    # === Tecno more ===
    ph(id="tecno_camon30pro",brand="Tecno",model="Camon 30 Pro",model_name="Camon 30 Pro",
      screen_size="6.78英寸",screen_type="AMOLED",resolution="2436x1080",refresh_rate="120Hz",
      chipset="Dimensity 8200 Ultimate",cpu_cores="8核",gpu="Mali-G610",ram="12GB",storage="256GB",storage_expandable=False,
      rear_camera_main="50MP",rear_camera_count="2摄",rear_camera_specs="50MP主摄(OIS)+50MP超广角",front_camera="50MP",video="4K@30fps",
      battery_capacity="5000mAh",charging_wired="70W",charging_wireless="无",fast_charging=True,
      os="Android 14",network_5g=True,sim_type="Nano-SIM",
      weight="188g",dimensions="163x76.3x7.7mm",water_resistance="IP54",material="素皮背板+塑料边框",
      fingerprint="屏下光学",face_unlock=True,nfc=True,infrared=False,headphone_jack=True,
      launch_date="2024-03",source="tecno-mobile.com",source_url=""),
    # === Honor flagship ===
    ph(id="honor_magicv3",brand="Honor",model="Magic V3",model_name="Magic V3",
      screen_size="7.92英寸",screen_type="Foldable LTPO AMOLED",resolution="2344x2156",refresh_rate="120Hz",
      chipset="Snapdragon 8 Gen 3",cpu_cores="8核",gpu="Adreno 750",ram="12GB",storage="256GB",storage_expandable=False,
      rear_camera_main="50MP",rear_camera_count="3摄",rear_camera_specs="50MP主摄(OIS)+50MP潜望长焦(3.5x)+40MP超广角",front_camera="20MP",video="4K@60fps",
      battery_capacity="5150mAh",charging_wired="66W",charging_wireless="50W",fast_charging=True,
      os="Android 14, MagicOS",network_5g=True,sim_type="Nano-SIM",
      weight="226g",dimensions="156.6x145.3x4.4mm(展开)",water_resistance="IPX8",material="玻璃背板+铝合金边框 超薄折叠",
      fingerprint="侧边",face_unlock=True,nfc=True,infrared=True,headphone_jack=False,
      launch_date="2024-07",source="honor.com",source_url=""),
]

added = 0
skipped = 0
for phone in new:
    key = (phone['model_name'], phone['brand'])
    if key not in existing_keys:
        existing.append(phone)
        existing_keys.add(key)
        added += 1
    else:
        skipped += 1

print(f"Batch 5: Added {added}, skipped {skipped}")

with open(DATA_PATH, 'w') as f:
    json.dump(existing, f, ensure_ascii=False, indent=2)

brands = {}
for p in existing:
    brands[p['brand']] = brands.get(p['brand'], 0) + 1
print(f"Total: {len(existing)} phones, {len(brands)} brands")
for b, c in sorted(brands.items(), key=lambda x: -x[1]):
    print(f"  {b}: {c}")
